[programs.localnet]
blop = "FWc9xvNjL9mTiUvVamm8DaYVHKT2aRW1n3VxmALKmQ5Z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nithsua/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
